#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
[[ "${TRACE:-}" != "" ]] && set -o xtrace

unset COMPOSE_FILE
unset COMPOSE_PROJECT_NAME

config=$(docker-compose config | yq .)
services=$(echo "${config}" | jq -r '.services | keys[]')

for service_name in ${services}; do
	service=$(echo "${config}" | jq ".services[\"${service_name}\"]")
    has_build_config=$(echo ${service} | jq -r 'has("build")')

    if [[ "${has_build_config}" != "true" ]]; then
        continue
    fi

    dockerfile=$(echo ${service} | jq -r '.build.dockerfile // "Dockerfile"')
	context=$(echo ${service} | jq -r '.build.context // "."')

	echo "##########"
	echo "Updating locks for service ${service_name} (context: ${context}, build manifest: ${dockerfile}):"
	echo "##########"

	cd ${context} # docker-compose config returns absolute path
    zbuild update -f ${dockerfile}
done
