// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/NiR-/zbuild/pkg/statesolver (interfaces: StateSolver)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	statesolver "github.com/NiR-/zbuild/pkg/statesolver"
	gomock "github.com/golang/mock/gomock"
	llb "github.com/moby/buildkit/client/llb"
	reflect "reflect"
)

// MockStateSolver is a mock of StateSolver interface
type MockStateSolver struct {
	ctrl     *gomock.Controller
	recorder *MockStateSolverMockRecorder
}

// MockStateSolverMockRecorder is the mock recorder for MockStateSolver
type MockStateSolverMockRecorder struct {
	mock *MockStateSolver
}

// NewMockStateSolver creates a new mock instance
func NewMockStateSolver(ctrl *gomock.Controller) *MockStateSolver {
	mock := &MockStateSolver{ctrl: ctrl}
	mock.recorder = &MockStateSolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStateSolver) EXPECT() *MockStateSolverMockRecorder {
	return m.recorder
}

// FromBuildContext mocks base method
func (m *MockStateSolver) FromBuildContext(arg0 ...llb.LocalOption) statesolver.ReadFileOpt {
	varargs := []interface{}{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FromBuildContext", varargs...)
	ret0, _ := ret[0].(statesolver.ReadFileOpt)
	return ret0
}

// FromBuildContext indicates an expected call of FromBuildContext
func (mr *MockStateSolverMockRecorder) FromBuildContext(arg0 ...interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromBuildContext", reflect.TypeOf((*MockStateSolver)(nil).FromBuildContext), arg0...)
}

// FromImage mocks base method
func (m *MockStateSolver) FromImage(arg0 string) statesolver.ReadFileOpt {
	ret := m.ctrl.Call(m, "FromImage", arg0)
	ret0, _ := ret[0].(statesolver.ReadFileOpt)
	return ret0
}

// FromImage indicates an expected call of FromImage
func (mr *MockStateSolverMockRecorder) FromImage(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FromImage", reflect.TypeOf((*MockStateSolver)(nil).FromImage), arg0)
}

// ReadFile mocks base method
func (m *MockStateSolver) ReadFile(arg0 context.Context, arg1 string, arg2 statesolver.ReadFileOpt) ([]byte, error) {
	ret := m.ctrl.Call(m, "ReadFile", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile
func (mr *MockStateSolverMockRecorder) ReadFile(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockStateSolver)(nil).ReadFile), arg0, arg1, arg2)
}
